# Generated by Django 6.0.4 on 2026-04-20 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'card_game',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('card_type', models.CharField(blank=True, max_length=80)),
                ('subtype', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('artist_name', models.CharField(blank=True, max_length=120)),
                ('attack', models.PositiveIntegerField(blank=True, null=True)),
                ('defense', models.PositiveIntegerField(blank=True, null=True)),
                ('hp', models.PositiveIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='catalog.cardgame')),
            ],
            options={
                'db_table': 'card',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=40)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='catalog.cardgame')),
            ],
            options={
                'db_table': 'card_set',
                'ordering': ('game__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CardVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector_number', models.CharField(blank=True, max_length=40)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('UNCOMMON', 'Uncommon'), ('RARE', 'Rare'), ('ULTRA_RARE', 'Ultra Rare'), ('SECRET_RARE', 'Secret Rare'), ('PROMO', 'Promo')], default='COMMON', max_length=40)),
                ('finish', models.CharField(choices=[('NORMAL', 'Normal'), ('HOLO', 'Holo'), ('REVERSE_HOLO', 'Reverse Holo'), ('SHINY', 'Shiny')], default='NORMAL', max_length=40)),
                ('language', models.CharField(default='en', max_length=20)),
                ('edition_label', models.CharField(blank=True, max_length=80)),
                ('is_first_edition', models.BooleanField(default=False)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.cardset')),
            ],
            options={
                'db_table': 'card_variant',
                'ordering': ('card__name', 'set__name', 'collector_number'),
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('image_hash', models.CharField(blank=True, max_length=128)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('card_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.cardvariant')),
            ],
            options={
                'db_table': 'card_image',
                'ordering': ('card_variant_id', '-is_primary', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['name'], name='card_name_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['game', 'name'], name='card_game_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(fields=('game', 'code'), name='unique_set_code_per_game'),
        ),
        migrations.AddIndex(
            model_name='cardvariant',
            index=models.Index(fields=['set', 'rarity'], name='variant_set_rarity_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvariant',
            index=models.Index(fields=['current_value'], name='variant_value_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardvariant',
            constraint=models.CheckConstraint(condition=models.Q(('current_value__gte', 0)), name='variant_current_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cardvariant',
            constraint=models.UniqueConstraint(fields=('card', 'set', 'collector_number', 'finish', 'language', 'edition_label', 'is_first_edition'), name='unique_card_variant_printing'),
        ),
    ]
