# Generated by Django 6.0.4 on 2026-04-20 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardimage',
            options={'ordering': ('card_variant_id',)},
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='catalog.cardvariant'),
        ),
    ]
