# Generated by Django 6.0.4 on 2026-04-20 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cardimage_options_alter_cardimage_card_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='is_primary',
        ),
    ]
