# Generated by Django 6.0.4 on 2026-04-23 22:49

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_cardimage_is_primary'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('name', name='gin_trgm_ops'), name='card_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('card_type', name='gin_trgm_ops'), name='card_type_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('subtype', name='gin_trgm_ops'), name='card_subtype_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('artist_name', name='gin_trgm_ops'), name='card_artist_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvariant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('collector_number', name='gin_trgm_ops'), name='variant_collector_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardvariant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('edition_label', name='gin_trgm_ops'), name='variant_edition_trgm_idx'),
        ),
    ]
