# Generated by Django 6.0.4 on 2026-04-20 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_cardimage_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('source_name', models.CharField(max_length=120)),
                ('captured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='catalog.cardvariant')),
            ],
            options={
                'db_table': 'price_snapshot',
                'ordering': ('-captured_at', '-id'),
                'indexes': [models.Index(fields=['card_variant', 'captured_at'], name='price_variant_captured_idx'), models.Index(fields=['source_name', 'captured_at'], name='price_source_captured_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='price_snapshot_price_non_negative')],
            },
        ),
    ]
