# Generated by Django 6.0.4 on 2026-04-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_card_card_name_trgm_idx_card_card_type_trgm_idx_and_more'),
        ('pricing', '0003_recalculate_current_value_from_recent_sales'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pricesnapshot',
            index=models.Index(fields=['card_variant', '-captured_at', '-id'], name='price_variant_latest_idx'),
        ),
    ]
