FAKE_CARDS = [
    {"id": 1, "name": "Charizard", "set_name": "Base Set", "rarity": "rare", "current_value": 320.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-01"},
    {"id": 2, "name": "Blastoise", "set_name": "Base Set", "rarity": "rare", "current_value": 180.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-02"},
    {"id": 3, "name": "Pikachu", "set_name": "Jungle", "rarity": "common", "current_value": 12.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-03"},
    {"id": 4, "name": "Mewtwo", "set_name": "Base Set", "rarity": "rare", "current_value": 210.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-04"},
    {"id": 5, "name": "Dark Charizard", "set_name": "Team Rocket", "rarity": "ultra", "current_value": 450.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-05"},
    {"id": 6, "name": "Lugia", "set_name": "Neo Genesis", "rarity": "secret", "current_value": 890.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-06"},
    {"id": 7, "name": "Blue-Eyes Dragon", "set_name": "Legend of Blue Eyes", "rarity": "rare", "current_value": 95.00, "image_url": "", "game": "Yu-Gi-Oh", "language": "English", "created_at": "2024-01-07"},
    {"id": 8, "name": "Dark Magician", "set_name": "Legend of Blue Eyes", "rarity": "rare", "current_value": 60.00, "image_url": "", "game": "Yu-Gi-Oh", "language": "English", "created_at": "2024-01-08"},
    {"id": 9, "name": "Exodia", "set_name": "Metal Raiders", "rarity": "ultra", "current_value": 130.00, "image_url": "", "game": "Yu-Gi-Oh", "language": "English", "created_at": "2024-01-09"},
    {"id": 10, "name": "Black Lotus", "set_name": "Alpha Edition", "rarity": "secret", "current_value": 5000.00, "image_url": "", "game": "Magic: The Gathering", "language": "English", "created_at": "2024-01-10"},
    {"id": 11, "name": "Lightning Bolt", "set_name": "Alpha Edition", "rarity": "uncommon", "current_value": 800.00, "image_url": "", "game": "Magic: The Gathering", "language": "English", "created_at": "2024-01-11"},
    {"id": 12, "name": "Ancestral Recall", "set_name": "Beta Edition", "rarity": "uncommon", "current_value": 3200.00, "image_url": "", "game": "Magic: The Gathering", "language": "English", "created_at": "2024-01-12"},
    {"id": 13, "name": "Venusaur", "set_name": "Base Set", "rarity": "rare", "current_value": 140.00, "image_url": "", "game": "Pokemon", "language": "Japanese", "created_at": "2024-01-13"},
    {"id": 14, "name": "Raichu", "set_name": "Fossil", "rarity": "uncommon", "current_value": 35.00, "image_url": "", "game": "Pokemon", "language": "Japanese", "created_at": "2024-01-14"},
    {"id": 15, "name": "Gengar", "set_name": "Fossil", "rarity": "rare", "current_value": 75.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-15"},
    {"id": 16, "name": "Mew", "set_name": "Promo", "rarity": "ultra", "current_value": 260.00, "image_url": "", "game": "Pokemon", "language": "English", "created_at": "2024-01-16"},
]

FAKE_LISTINGS = [
    {"id": 1, "card": FAKE_CARDS[0], "price_per_unit": 310.00, "quantity": 1, "seller": {"username": "pokefan99"}, "condition": "Near Mint"},
    {"id": 2, "card": FAKE_CARDS[4], "price_per_unit": 440.00, "quantity": 2, "seller": {"username": "darktrader"}, "condition": "Lightly Played"},
    {"id": 3, "card": FAKE_CARDS[5], "price_per_unit": 875.00, "quantity": 1, "seller": {"username": "legendcards"}, "condition": "Near Mint"},
    {"id": 4, "card": FAKE_CARDS[9], "price_per_unit": 4800.00, "quantity": 1, "seller": {"username": "mtgvault"}, "condition": "Near Mint"},
    {"id": 5, "card": FAKE_CARDS[6], "price_per_unit": 90.00, "quantity": 3, "seller": {"username": "yugifan"}, "condition": "Good"},
    {"id": 6, "card": FAKE_CARDS[15], "price_per_unit": 255.00, "quantity": 1, "seller": {"username": "pokefan99"}, "condition": "Near Mint"},
    {"id": 7, "card": FAKE_CARDS[1], "price_per_unit": 170.00, "quantity": 2, "seller": {"username": "cardvault"}, "condition": "Good"},
    {"id": 8, "card": FAKE_CARDS[3], "price_per_unit": 200.00, "quantity": 1, "seller": {"username": "mtgvault"}, "condition": "Near Mint"},
    {"id": 9, "card": FAKE_CARDS[7], "price_per_unit": 55.00, "quantity": 4, "seller": {"username": "yugifan"}, "condition": "Lightly Played"},
    {"id": 10, "card": FAKE_CARDS[10], "price_per_unit": 780.00, "quantity": 1, "seller": {"username": "legendcards"}, "condition": "Near Mint"},
]
