# Generated by Django 6.0.4 on 2026-04-20 10:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_cardimage_is_primary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('MINT', 'Mint'), ('NEAR_MINT', 'Near Mint'), ('LIGHTLY_PLAYED', 'Lightly Played'), ('MODERATELY_PLAYED', 'Moderately Played'), ('HEAVILY_PLAYED', 'Heavily Played'), ('DAMAGED', 'Damaged')], max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('acquired_at', models.DateField(default=django.utils.timezone.localdate)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('card_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='catalog.cardvariant')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_item',
                'ordering': ('owner_id', 'card_variant_id', 'condition'),
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ADD', 'Add'), ('INCREASE', 'Increase'), ('DECREASE', 'Decrease'), ('RESERVE', 'Reserve'), ('RELEASE', 'Release'), ('PURCHASE', 'Purchase'), ('ADJUST', 'Adjust')], max_length=40)),
                ('quantity_delta', models.IntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_history_entries', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='inventory.inventoryitem')),
            ],
            options={
                'db_table': 'inventory_history',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'card_variant'], name='inventory_owner_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['owner', 'is_for_sale'], name='inventory_owner_sale_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('owner', 'card_variant', 'condition'), name='unique_inventory_owner_variant_condition'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='inventory_reserved_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('quantity'))), name='inventory_reserved_not_above_quantity'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__isnull', True), ('purchase_price__gte', 0), _connector='OR'), name='inventory_purchase_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['inventory_item', 'created_at'], name='history_item_created_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryhistory',
            index=models.Index(fields=['created_by', 'created_at'], name='history_actor_created_idx'),
        ),
    ]
