# Generated by Django 6.0.4 on 2026-04-23 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_card_card_name_trgm_idx_card_card_type_trgm_idx_and_more'),
        ('inventory', '0003_remove_inventoryitem_is_for_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(condition=models.Q(('quantity__gt', 0)), fields=['owner', 'card_variant', 'condition'], name='inventory_active_owner_idx'),
        ),
    ]
