# Generated by Django 6.0.4 on 2026-04-20 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_remove_cardimage_is_primary'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('SOLD_OUT', 'Sold Out'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=40)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='market_listings', to='inventory.inventoryitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_listing',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=40)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_order',
                'ordering': ('-created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='catalog.cardvariant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='marketplace.marketlisting')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='marketplace.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_line',
                'ordering': ('purchase_order_id', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['seller', 'status'], name='listing_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['status', 'unit_price'], name='listing_status_price_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(fields=['inventory_item', 'status'], name='listing_inventory_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='listing_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='listing_available_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__lte', models.F('quantity'))), name='listing_available_not_above_quantity'),
        ),
        migrations.AddConstraint(
            model_name='marketlisting',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='listing_price_non_negative'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['buyer', 'status'], name='order_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['seller', 'status'], name='order_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status', 'created_at'], name='order_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('buyer', models.F('seller')), _negated=True), name='order_buyer_not_seller'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order'], name='order_line_order_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['listing'], name='order_line_listing_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['card_variant'], name='order_line_variant_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_line_price_non_negative'),
        ),
    ]
