# Generated by Django 6.0.4 on 2026-04-23 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventoryitem_inventory_active_owner_idx'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(condition=models.Q(('quantity_available__gt', 0), ('status', 'ACTIVE')), fields=['-created_at', 'id'], name='listing_active_new_idx'),
        ),
        migrations.AddIndex(
            model_name='marketlisting',
            index=models.Index(condition=models.Q(('quantity_available__gt', 0), ('status', 'ACTIVE')), fields=['inventory_item'], name='listing_active_inventory_idx'),
        ),
    ]
